name: CI

on:
  push:
    branches: [master, ci]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install other dependency on windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: powershell
        run: |
          git clone https://github.com/microsoft/vcpkg C:/src/vcpkg
          C:/src/vcpkg/bootstrap-vcpkg.bat
          C:/src/vcpkg/vcpkg install libpng

      - name: Install packages
        run: yarn upgrade --dev

      - name: Prebuild
        run: yarn build-prebuild

      - name: Build
        run: yarn build

      - name: Run test suite
        run: yarn test

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-${{ matrix.os }}
          path: prebuilds/**/*.tar.gz
