name: CI

on:
  push:
    tags:
      - "v*.*.*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: upgrade --dev

      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Publish
        uses: borales/actions-yarn@v2.0.0
        with:
          auth-token: ${{ secrets.NPM_TOKEN }}
          cmd: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
